import type {
  GraphNode, GraphEdge, SDIMetrics, IntelligenceFeedItem,
  RiskIndicator, ScenarioResult, EntityDetail, ShadowOntologySignal
} from '@/types';

export const GRAPH_NODES: GraphNode[] = [
  // Countries
  { id: 'IND', label: 'India', type: 'country', risk: 42, influence: 78, description: 'Strategic pivotal democracy and emerging global power' },
  { id: 'CHN', label: 'China', type: 'country', risk: 71, influence: 91, description: 'Largest authoritarian state with global economic and military ambitions' },
  { id: 'USA', label: 'United States', type: 'country', risk: 55, influence: 95, description: 'Dominant superpower with global military and economic reach' },
  { id: 'RUS', label: 'Russia', type: 'country', risk: 84, influence: 72, description: 'Nuclear power engaged in active territorial conflicts' },
  { id: 'PAK', label: 'Pakistan', type: 'country', risk: 77, influence: 38, description: 'Nuclear state with deep instability and proxy conflict involvement' },
  { id: 'IRN', label: 'Iran', type: 'country', risk: 73, influence: 55, description: 'Regional power under sanctions with proxy network influence' },
  { id: 'ISR', label: 'Israel', type: 'country', risk: 68, influence: 61, description: 'Technological military power in volatile regional context' },
  { id: 'SAU', label: 'Saudi Arabia', type: 'country', risk: 52, influence: 65, description: 'Key hydrocarbon exporter and regional security broker' },
  { id: 'EU', label: 'European Union', type: 'country', risk: 47, influence: 79, description: 'Multi-state bloc navigating energy, migration, and security pressures' },
  { id: 'JPN', label: 'Japan', type: 'country', risk: 35, influence: 69, description: 'High-technology democracy in Indo-Pacific security architecture' },
  { id: 'KOR', label: 'South Korea', type: 'country', risk: 45, influence: 56, description: 'Tech powerhouse facing North Korean missile threats' },
  { id: 'PRK', label: 'North Korea', type: 'country', risk: 88, influence: 42, description: 'Rogue nuclear state with active ICBM testing program' },

  // Organizations
  { id: 'NATO', label: 'NATO', type: 'organization', risk: 48, influence: 85, description: 'Western military alliance expanding amid Russian aggression' },
  { id: 'SCO', label: 'SCO', type: 'organization', risk: 55, influence: 67, description: 'Eurasian security bloc led by China and Russia' },
  { id: 'QUAD', label: 'QUAD', type: 'organization', risk: 30, influence: 62, description: 'Indo-Pacific security dialogue: India, USA, Japan, Australia' },
  { id: 'BRICS', label: 'BRICS+', type: 'organization', risk: 40, influence: 70, description: 'Emerging economies bloc seeking de-dollarization' },
  { id: 'UN', label: 'United Nations', type: 'organization', risk: 25, influence: 60, description: 'Multilateral body with diminishing enforcement capacity' },

  // Resources
  { id: 'OIL', label: 'Global Oil', type: 'resource', risk: 65, influence: 88, description: 'Strategic hydrocarbon resource with embedded geopolitical leverage' },
  { id: 'REM', label: 'Rare Earth Metals', type: 'resource', risk: 72, influence: 82, description: 'Critical materials for semiconductors and defense systems' },
  { id: 'SEM', label: 'Semiconductors', type: 'resource', risk: 69, influence: 86, description: 'Foundational technology for all digital and defense systems' },
  { id: 'WTR', label: 'Water Resources', type: 'resource', risk: 58, influence: 65, description: 'Transboundary water stress in Asia and Middle East' },

  // Technologies
  { id: 'AI', label: 'Artificial Intelligence', type: 'technology', risk: 60, influence: 92, description: 'Decisive emerging technology shaping military and economic power' },
  { id: 'CYB', label: 'Cyber Operations', type: 'technology', risk: 78, influence: 83, description: 'Asymmetric warfare domain with escalating state activity' },
  { id: 'HYP', label: 'Hypersonics', type: 'technology', risk: 82, influence: 75, description: 'Advanced missile technology disrupting deterrence calculus' },
  { id: 'SPC', label: 'Space Assets', type: 'technology', risk: 55, influence: 80, description: 'Contested orbital domain with dual-use satellite infrastructure' },

  // Actors
  { id: 'BRI', label: 'Belt & Road Initiative', type: 'event', risk: 63, influence: 77, description: 'Chinese infrastructure program creating debt-trap dependencies' },
  { id: 'UKR', label: 'Ukraine Conflict', type: 'event', risk: 91, influence: 88, description: 'Active kinetic conflict reshaping European security order' },
  { id: 'TWN', label: 'Taiwan Strait', type: 'event', risk: 85, influence: 90, description: 'Critical flashpoint for US-China confrontation and global chip supply' },
];

export const GRAPH_EDGES: GraphEdge[] = [
  { id: 'e1', source: 'IND', target: 'CHN', type: 'rivalry', weight: 78, active: true, label: 'Border Rivalry' },
  { id: 'e2', source: 'IND', target: 'USA', type: 'alliance', weight: 70, active: true, label: 'Strategic Partnership' },
  { id: 'e3', source: 'IND', target: 'RUS', type: 'trade', weight: 65, active: true, label: 'Defense & Energy Trade' },
  { id: 'e4', source: 'IND', target: 'QUAD', type: 'alliance', weight: 60, active: true, label: 'Member' },
  { id: 'e5', source: 'IND', target: 'BRICS', type: 'alliance', weight: 55, active: true, label: 'Member' },
  { id: 'e6', source: 'IND', target: 'PAK', type: 'conflict', weight: 85, active: true, label: 'Hostility' },
  { id: 'e7', source: 'CHN', target: 'USA', type: 'rivalry', weight: 88, active: true, label: 'Strategic Competition' },
  { id: 'e8', source: 'CHN', target: 'RUS', type: 'alliance', weight: 75, active: true, label: 'No-limits Partnership' },
  { id: 'e9', source: 'CHN', target: 'TWN', type: 'conflict', weight: 92, active: true, label: 'Territorial Claim' },
  { id: 'e10', source: 'CHN', target: 'REM', type: 'dependency', weight: 89, active: true, label: 'Controls Supply' },
  { id: 'e11', source: 'CHN', target: 'BRI', type: 'dependency', weight: 95, active: true, label: 'Leads Initiative' },
  { id: 'e12', source: 'CHN', target: 'SCO', type: 'alliance', weight: 80, active: true, label: 'Co-leads' },
  { id: 'e13', source: 'USA', target: 'NATO', type: 'alliance', weight: 90, active: true, label: 'Leads' },
  { id: 'e14', source: 'USA', target: 'SEM', type: 'dependency', weight: 85, active: true, label: 'Controls Design' },
  { id: 'e15', source: 'USA', target: 'TWN', type: 'alliance', weight: 78, active: true, label: 'Security Guarantor' },
  { id: 'e16', source: 'RUS', target: 'UKR', type: 'conflict', weight: 98, active: true, label: 'Active War' },
  { id: 'e17', source: 'RUS', target: 'OIL', type: 'dependency', weight: 88, active: true, label: 'Major Exporter' },
  { id: 'e18', source: 'RUS', target: 'HYP', type: 'dependency', weight: 82, active: true, label: 'Deployed Systems' },
  { id: 'e19', source: 'PAK', target: 'CHN', type: 'alliance', weight: 88, active: true, label: 'All-weather Friend' },
  { id: 'e20', source: 'IRN', target: 'RUS', type: 'alliance', weight: 70, active: true, label: 'Drone Supply Chain' },
  { id: 'e21', source: 'IRN', target: 'SAU', type: 'conflict', weight: 72, active: true, label: 'Regional Rivalry' },
  { id: 'e22', source: 'SAU', target: 'OIL', type: 'dependency', weight: 95, active: true, label: 'Largest Exporter' },
  { id: 'e23', source: 'NATO', target: 'RUS', type: 'conflict', weight: 82, active: true, label: 'Strategic Opposition' },
  { id: 'e24', source: 'USA', target: 'AI', type: 'dependency', weight: 85, active: true, label: 'Technology Leader' },
  { id: 'e25', source: 'CHN', target: 'AI', type: 'dependency', weight: 80, active: true, label: 'Technology Rival' },
  { id: 'e26', source: 'CYB', target: 'RUS', type: 'dependency', weight: 78, active: true, label: 'State Actor' },
  { id: 'e27', source: 'CYB', target: 'CHN', type: 'dependency', weight: 80, active: true, label: 'State Actor' },
  { id: 'e28', source: 'PRK', target: 'CHN', type: 'dependency', weight: 72, active: true, label: 'Economic Lifeline' },
  { id: 'e29', source: 'PRK', target: 'HYP', type: 'dependency', weight: 65, active: true, label: 'Developing Capability' },
  { id: 'e30', source: 'EU', target: 'RUS', type: 'sanction', weight: 85, active: true, label: 'Sanctions Regime' },
  { id: 'e31', source: 'IND', target: 'OIL', type: 'dependency', weight: 70, active: true, label: 'Major Importer' },
  { id: 'e32', source: 'TWN', target: 'SEM', type: 'dependency', weight: 92, active: true, label: 'Manufactures 60%' },
  { id: 'e33', source: 'JPN', target: 'QUAD', type: 'alliance', weight: 68, active: true, label: 'Member' },
  { id: 'e34', source: 'IND', target: 'WTR', type: 'conflict', weight: 60, active: true, label: 'Brahmaputra Tension' },
  { id: 'e35', source: 'CHN', target: 'WTR', type: 'dependency', weight: 65, active: true, label: 'Upstream Control' },
];

export const SDI_METRICS: SDIMetrics = {
  overall: 67,
  alertCount: 14,
  lastRecalculated: new Date(Date.now() - 3 * 60000).toISOString(),
  domains: [
    { domain: 'geopolitics', score: 74, trend: 'rising', anomalies: 5, lastUpdate: new Date(Date.now() - 5 * 60000).toISOString() },
    { domain: 'economics', score: 58, trend: 'stable', anomalies: 3, lastUpdate: new Date(Date.now() - 8 * 60000).toISOString() },
    { domain: 'defense', score: 81, trend: 'rising', anomalies: 6, lastUpdate: new Date(Date.now() - 2 * 60000).toISOString() },
    { domain: 'technology', score: 65, trend: 'rising', anomalies: 4, lastUpdate: new Date(Date.now() - 10 * 60000).toISOString() },
    { domain: 'climate', score: 42, trend: 'falling', anomalies: 1, lastUpdate: new Date(Date.now() - 15 * 60000).toISOString() },
    { domain: 'society', score: 53, trend: 'stable', anomalies: 2, lastUpdate: new Date(Date.now() - 12 * 60000).toISOString() },
  ],
};

export const INTELLIGENCE_FEED: IntelligenceFeedItem[] = [
  {
    id: 'f1',
    title: 'China Deploys Additional Naval Assets Near Taiwan Strait',
    summary: 'PLA Navy has positioned 12 additional warships in proximity to Taiwan Strait amid heightened diplomatic tensions following US arms sale confirmation.',
    domain: 'defense',
    severity: 'critical',
    source: 'OSINT Composite',
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    entities: ['CHN', 'TWN', 'USA'],
    sdiImpact: 15,
    verified: true,
    tags: ['naval', 'taiwan', 'escalation'],
  },
  {
    id: 'f2',
    title: 'India-Russia Bilateral Trade Reaches $65B Despite Western Sanctions Pressure',
    summary: 'Economic data confirms record bilateral trade driven by discounted Russian crude, fertilizers, and defense systems, creating strategic interdependency.',
    domain: 'economics',
    severity: 'high',
    source: 'Ministry of Commerce Data',
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    entities: ['IND', 'RUS', 'EU'],
    sdiImpact: 8,
    verified: true,
    tags: ['trade', 'sanctions', 'energy'],
  },
  {
    id: 'f3',
    title: 'North Korea Tests New ICBM Capable of Reaching Continental US',
    summary: 'Hwasong-19 variant demonstrates reentry vehicle capable of deploying multiple warheads. South Korean military confirms 74-minute flight over Japanese EEZ.',
    domain: 'defense',
    severity: 'critical',
    source: 'US Strategic Command / JGSDF',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    entities: ['PRK', 'USA', 'JPN', 'KOR'],
    sdiImpact: 18,
    verified: true,
    tags: ['nuclear', 'missile', 'icbm'],
  },
  {
    id: 'f4',
    title: 'Pakistan Army Chief Meets ISI Leadership Over Cross-Border Infiltration Surge',
    summary: 'Intelligence intercepts suggest coordinated push to destabilize Kashmir valley ahead of scheduled elections. India activates forward surveillance posts.',
    domain: 'geopolitics',
    severity: 'high',
    source: 'Intelligence Assessment (Classified)',
    timestamp: new Date(Date.now() - 67 * 60000).toISOString(),
    entities: ['PAK', 'IND'],
    sdiImpact: 12,
    verified: false,
    tags: ['kashmir', 'infiltration', 'pakistan'],
  },
  {
    id: 'f5',
    title: 'Chinese Cyber Unit APT41 Targets Indian Power Grid Infrastructure',
    summary: 'CERT-In confirms intrusion attempts against 6 major power distribution nodes attributed to Chinese state actor. No outage recorded but persistence mechanisms found.',
    domain: 'technology',
    severity: 'critical',
    source: 'CERT-In / NCIIPC',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    entities: ['CHN', 'IND', 'CYB'],
    sdiImpact: 14,
    verified: true,
    tags: ['cyberattack', 'infrastructure', 'apt41'],
  },
  {
    id: 'f6',
    title: 'OPEC+ Production Cut Signals Saudi-Russia Strategic Coordination on Oil Price',
    summary: 'Unexpected 1.2M barrel/day cut defies US pressure, driving Brent above $95. Analysis suggests coordinated economic signaling against Western energy policy.',
    domain: 'economics',
    severity: 'high',
    source: 'IEA / Bloomberg Intelligence',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    entities: ['SAU', 'RUS', 'OIL', 'USA'],
    sdiImpact: 10,
    verified: true,
    tags: ['opec', 'oil', 'energy-war'],
  },
  {
    id: 'f7',
    title: 'BRICS Nations Advance Alternative Payment System to Bypass SWIFT',
    summary: 'Technical working group finalizes cross-border settlement protocol connecting 9 central banks. Could process $200B annually by 2026 without USD dependency.',
    domain: 'economics',
    severity: 'medium',
    source: 'BRICS Secretariat / Reuters',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    entities: ['BRICS', 'CHN', 'IND', 'RUS'],
    sdiImpact: 7,
    verified: true,
    tags: ['dedollarization', 'brics', 'swift'],
  },
  {
    id: 'f8',
    title: 'India Successfully Tests Agni-VI MIRV Capability in Bay of Bengal',
    summary: 'Extended range ICBM demonstrates Multiple Independently Targetable Reentry Vehicle technology. Range estimated at 12,000 km with 10 warhead payload capacity.',
    domain: 'defense',
    severity: 'medium',
    source: 'DRDO / PIB',
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    entities: ['IND', 'HYP'],
    sdiImpact: 9,
    verified: true,
    tags: ['missile', 'agni', 'nuclear-deterrence'],
  },
  {
    id: 'f9',
    title: 'Arctic Shipping Route Sees 40% Volume Increase as Permafrost Recession Accelerates',
    summary: 'Russia and China jointly operate 14 ice-class vessels along Northern Sea Route. Bypasses Suez, reducing China-Europe transit time by 18 days.',
    domain: 'climate',
    severity: 'medium',
    source: 'Arctic Council / NSIDC',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    entities: ['RUS', 'CHN', 'EU'],
    sdiImpact: 6,
    verified: true,
    tags: ['arctic', 'shipping', 'climate-geopolitics'],
  },
  {
    id: 'f10',
    title: 'AI Governance Breakdown: UN Framework Talks Collapse Over Military AI Definitions',
    summary: 'Geneva negotiations fail as US, China, and Russia reject binding limitations on autonomous weapons systems. Expert consensus identifies 2027 as critical threshold year.',
    domain: 'technology',
    severity: 'high',
    source: 'UN GGE / International Committee ICRC',
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    entities: ['UN', 'AI', 'USA', 'CHN', 'RUS'],
    sdiImpact: 11,
    verified: true,
    tags: ['ai-governance', 'autonomous-weapons', 'un'],
  },
];

export const RISK_INDICATORS: RiskIndicator[] = [
  { region: 'East Asia', country: 'CHN-TWN', riskScore: 88, domains: { defense: 92, economics: 78, technology: 85 }, trend: 'escalating', activeAlerts: 6 },
  { region: 'Eastern Europe', country: 'RUS-UKR', riskScore: 94, domains: { defense: 98, economics: 85, geopolitics: 91 }, trend: 'escalating', activeAlerts: 9 },
  { region: 'South Asia', country: 'IND-PAK', riskScore: 71, domains: { defense: 80, geopolitics: 75, society: 62 }, trend: 'stable', activeAlerts: 4 },
  { region: 'Middle East', country: 'IRN-ISR', riskScore: 78, domains: { defense: 85, geopolitics: 80, economics: 60 }, trend: 'escalating', activeAlerts: 5 },
  { region: 'Korean Peninsula', country: 'PRK-KOR', riskScore: 82, domains: { defense: 90, geopolitics: 78, technology: 70 }, trend: 'stable', activeAlerts: 3 },
  { region: 'South China Sea', riskScore: 73, domains: { defense: 80, economics: 70, geopolitics: 75 }, trend: 'escalating', activeAlerts: 4 },
  { region: 'Sahel Region', riskScore: 68, domains: { society: 80, geopolitics: 72, climate: 75 }, trend: 'escalating', activeAlerts: 3 },
  { region: 'Indo-Pacific', riskScore: 62, domains: { defense: 70, economics: 65, geopolitics: 60 }, trend: 'stable', activeAlerts: 2 },
];

export const SCENARIO_RESULTS: ScenarioResult[] = [
  {
    id: 's1',
    title: 'Taiwan Strait Military Escalation',
    probability: 34,
    timeframe: '12-18 months',
    impact: 'critical',
    affectedDomains: ['defense', 'economics', 'technology', 'geopolitics'],
    keyActors: ['CHN', 'USA', 'TWN', 'JPN'],
    description: 'PLA initiates naval blockade followed by amphibious landing operations against Taiwan, triggering US Article 5-equivalent response and global semiconductor supply chain collapse.',
    mitigations: [
      'Accelerate domestic semiconductor capacity (India Semiconductor Mission)',
      'Strengthen QUAD operational readiness and joint response protocols',
      'Pre-position strategic reserves of critical technology components',
      'Engage Beijing through backchannel diplomacy via BRICS framework',
    ],
    earlyWarningSignals: [
      'PLA naval exercise scale exceeds 3x annual average',
      'Taiwan defense budget increase above 3% GDP',
      'TSMC leadership relocates or splits operations',
      'US carrier battle group redeployment to Pacific',
    ],
  },
  {
    id: 's2',
    title: 'India-China Himalayan Conflict Escalation',
    probability: 28,
    timeframe: '6-24 months',
    impact: 'critical',
    affectedDomains: ['defense', 'geopolitics', 'economics'],
    keyActors: ['IND', 'CHN', 'PAK', 'USA'],
    description: 'LAC friction point in Arunachal Pradesh escalates to brigade-level engagement following China dam construction on Brahmaputra. Pakistan opens second front in Kashmir.',
    mitigations: [
      'Activate bilateral hotlines and Doklam-style disengagement protocol',
      'Position Indian Mountain Strike Corps in forward bases',
      'Invoke US-India defense partnership for ISR support',
      'Engage ASEAN and SCO neutral parties for mediation',
    ],
    earlyWarningSignals: [
      'Chinese construction activity at Arunachal forward positions increases',
      'Pakistan Army mobilizes from Sialkot cantonment',
      'Indian Air Force activates forward bases in Leh and Tezpur',
      'Chinese state media tone toward India becomes adversarial',
    ],
  },
  {
    id: 's3',
    title: 'Global Semiconductor Shock from Cascading Restrictions',
    probability: 52,
    timeframe: '3-9 months',
    impact: 'high',
    affectedDomains: ['technology', 'economics', 'defense'],
    keyActors: ['USA', 'CHN', 'TWN', 'KOR'],
    description: 'US expands chip export controls to include advanced packaging while China retaliates with rare earth metal export restrictions, triggering global tech sector supply chain crisis.',
    mitigations: [
      'Accelerate India Semiconductor Mission Phase II investments',
      'Secure alternative rare earth supply agreements (Australia, Africa)',
      'Form QUAD semiconductor sharing and co-production framework',
      'Build 12-month strategic stockpile of critical components',
    ],
    earlyWarningSignals: [
      'China rare earth export volumes drop >20% month-over-month',
      'US Commerce Dept. entity list additions spike',
      'TSMC Fab utilization drops below 80%',
      'Spot price of gallium or germanium exceeds 3x baseline',
    ],
  },
];

export const ENTITY_DETAILS: Record<string, EntityDetail> = {
  IND: {
    id: 'IND',
    name: 'India',
    type: 'country',
    description: 'Largest democracy and fifth-largest economy. Pursuing strategic autonomy via multi-alignment. Indo-Pacific pivot, defense modernization, and technology sovereignty are core objectives.',
    riskScore: 42,
    influenceScore: 78,
    connections: 12,
    relatedEntities: [
      { id: 'CHN', name: 'China', relation: 'Border Rivalry', weight: 78 },
      { id: 'USA', name: 'United States', relation: 'Strategic Partner', weight: 70 },
      { id: 'RUS', name: 'Russia', relation: 'Defense/Energy Partner', weight: 65 },
      { id: 'PAK', name: 'Pakistan', relation: 'Active Hostility', weight: 85 },
      { id: 'QUAD', name: 'QUAD', relation: 'Member', weight: 60 },
    ],
    timeline: [
      { date: '2024-06', event: 'General Election - NDA third term', impact: 'low' },
      { date: '2024-09', event: 'India-China LAC disengagement at Depsang-Demchok', impact: 'medium' },
      { date: '2024-12', event: 'Agni-VI MIRV test successful', impact: 'medium' },
      { date: '2025-02', event: 'India-Russia oil trade record $65B', impact: 'high' },
      { date: '2025-06', event: 'APT41 cyberattack on power grid detected', impact: 'critical' },
    ],
    metrics: [
      { label: 'GDP', value: '$3.7T', trend: 'up' },
      { label: 'Defense Budget', value: '$81.4B', trend: 'up' },
      { label: 'SDI Score', value: 42, trend: 'stable' },
      { label: 'Strategic Influence', value: '78/100', trend: 'up' },
      { label: 'Nuclear Warheads', value: 172, trend: 'up' },
      { label: 'Active Personnel', value: '1.45M', trend: 'stable' },
    ],
  },
};

export const SHADOW_ONTOLOGY_SIGNALS: ShadowOntologySignal[] = [
  {
    id: 'so1',
    entity: 'China',
    officialNarrative: 'Peaceful rise, non-interference in internal affairs',
    groundReality: 'Active maritime expansion, debt-trap diplomacy, Taiwan coercion, supply chain weaponization',
    dissonanceScore: 87,
    domain: 'geopolitics',
    detectedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    confidence: 94,
  },
  {
    id: 'so2',
    entity: 'Russia',
    officialNarrative: 'Special Military Operation is liberation, not invasion',
    groundReality: 'Systematic destruction of civilian infrastructure, territorial annexation, nuclear saber-rattling',
    dissonanceScore: 95,
    domain: 'defense',
    detectedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    confidence: 99,
  },
  {
    id: 'so3',
    entity: 'Pakistan',
    officialNarrative: 'Committed to counter-terrorism and regional peace',
    groundReality: 'State-sponsored terror infrastructure, ISI support for militant proxies, nuclear proliferation risk',
    dissonanceScore: 83,
    domain: 'defense',
    detectedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    confidence: 88,
  },
  {
    id: 'so4',
    entity: 'United States',
    officialNarrative: 'Committed to rules-based international order',
    groundReality: 'Selective enforcement of multilateral frameworks, unilateral sanctions regime, AI weapons development',
    dissonanceScore: 55,
    domain: 'geopolitics',
    detectedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    confidence: 72,
  },
  {
    id: 'so5',
    entity: 'Saudi Arabia',
    officialNarrative: 'Vision 2030 economic reform and human rights improvements',
    groundReality: 'Persistent journalist suppression, Yemen proxy conflict, OPEC+ coordination with Russia',
    dissonanceScore: 68,
    domain: 'society',
    detectedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    confidence: 81,
  },
];

export const SDI_HISTORY = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 24 * 3600000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  overall: Math.floor(55 + Math.random() * 20),
  defense: Math.floor(65 + Math.random() * 25),
  geopolitics: Math.floor(60 + Math.random() * 22),
  economics: Math.floor(45 + Math.random() * 25),
  technology: Math.floor(50 + Math.random() * 25),
}));
